# Generated by Django 5.1.1 on 2024-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="change_rate_percent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exchange",
            name="enter_fee",
            field=models.IntegerField(default=0),
        ),
    ]
