# Generated by Django 5.1.1 on 2024-11-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_exchange_change_rate_percent_exchange_enter_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchange",
            name="coin_price",
            field=models.IntegerField(default=0),
        ),
    ]
